- hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Update repositories cache and install "fping" package
      apt:
        name: fping
        update_cache: yes

    - name: Read from CSV file and return a dictionary
      delegate_to: localhost
      read_csv:
        path: ifs_pd20compute4.csv
        key: var_host_name
        dialect: excel-tab  
      register: hosts

    - set_fact:
        dict2: '{{ item.value | dict2items | rejectattr("key", "eq", "var_host_name") | rejectattr("key", "match", ".+_mask") | list | items2dict }}'
      with_dict:
        - "{{ hosts.dict }}"
      when:
        - inventory_hostname == item.key

    - name: Testing the availability of gateways
      vars: 
        array2: "{{ dict2.values() | list }}"
      shell: "fping -S {{ item.key }} {{ item.value }}"
      with_dict:
        - "{{ dict(array2 | slice(array2 | length //2)) }}"
      when:
        - dict2 is defined
